### PR TITLE
Correct front end changes

### PR DESCRIPTION
**Pull request by Thexumaker**
Sorry about the other pull request, I've never really used git before or done open source but I think this has the correct changes.
- Added Flexbox for individual websites
-Centered main text
-Still need to switch Social media links to logos.

### CODE REVIEW

**Comment by ubershmekel** [comment]
Hi @Thexumaker thank you for your work on this. I like the centering and colors.

* I see you decided to avoid having cards and now each site shows up as almost the full width of the screen. Is this change intentional? The current live version shows 3 cards on each row when the window width permits.
* There is an issue with the title of cards being a bit too subtle, and squished between the site screenshots from above and below. It also isn't clear which card the title belongs to (above or below). See image.

Screen Shot 2020-07-04 at 2 48 56 PM

**Comment by Thexumaker** [comment]
Hi, I'm not sure why the changes aren't showing up on your end but it should look somewhat like this:
Screen Shot 2020-07-04 at 9 09 45 AM

Let me double check to see if maybe I'm missing something

**Comment by Thexumaker** [comment]
I just realized that the changes I made in build-html weren't saved, but the latest pull request should have the fixed version of the cards.

**Comment by Thexumaker** [comment]
Hi just wondering if the newest changes were good enough or if there's anything I should look to change.
Thanks!

**Comment by ubershmekel** [comment]
Sorry for the delay. @Thexumaker I would prefer if the card titles were somehow always visible. I would like this site to cater to people that are quickly scrolling through or searching for words in the page. The slow animation and hidden text makes consuming the information require more manual work.

Otherwise we could push this through. Looks good.

**Comment by Thexumaker** [comment]
Just removed the transitions!

**Comment by ubershmekel** [comment]
Looks good. Let's ship it. Thank you @Thexumaker !

**Pull request merged**
